baseURL = '/'
languageCode = 'ja-JP'
title = 'DeFiGeek Community'
# theme = ""

# language
DefaultContentLanguage = "ja"

[languages]
  [languages.ja]
    title = "DeFiGeek Community"
    languageName = "JP"
    weight = 1
  [languages.en]
    title = "DeFiGeek Community"
    languageName = "EN"
    weight = 2
